### ISSUE TITLE
[Solved] Bad format with NBC.com subs

### ISSUE THREAD

**Issue by rafamerino** [odinuge/tt-to-subrip#1]
Hi,

Thanks for your work, it's very helpful.

When I use your script to convert NBC subs, I get this in SRT:

_22
**00:01:07:06** --> 00:01:07,190
Sub text_

Instead of:

_718
**00:46:14,538** --> 00:46:16,005
Sub text_

Looks identical, but the problem is NBC original subs are using time format "HH:MM:SS**:**MILLS" (note the "colon") instead typical format from most subs "HH:MM:SS**,**MILLS" (note the "comma"). 
Problem is actual video software is no capable to manage correctly subtitles with no comma.

There is any way to solve this?

Here's some raw subs from NBC.com, for clarification:

```
<p begin="00:00:06:00" end="00:00:06:19" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="50.63% 5.33%">>> Steve: FROM STUDIO 6B IN</p>
<p begin="00:00:06:19" end="00:00:07:19" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="58.13% 5.33%">ROCKEFELLER CENTER IN THE HEART</p>
<p begin="00:00:07:19" end="00:00:09:05" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="50.63% 5.33%">OF NEW YORK CITY, IT'S "THE</p>
<p begin="00:00:09:05" end="00:00:09:24" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="39.38% 5.33%">TONIGHT SHOW STARRING</p>
<p begin="00:00:09:24" end="00:00:18:04" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="26.25% 5.33%">JIMMY FALLON."</p>
<p begin="00:00:18:04" end="00:00:18:27" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="50.63% 5.33%">TONIGHT, JOIN JIMMY AND HIS</p>
<p begin="00:00:18:27" end="00:00:19:10" region="rollup3" style="basic" tts:origin="20% 84.67%" tts:extent="16.88% 5.33%">GUESTS --</p>
```

PS: I've used this in windows with [awk port](http://gnuwin32.sourceforge.net/packages/gawk.htm):
_**type subs.en.tt | awk -f tt-to-subrip.awk > subs.en.srt**_

Thanks for your time.

**Comment by odinuge** [comment]
Thanks for the feedback!

That is kinda strange.. ill look at it as fast as i can!

**Comment by odinuge** [comment]
Hi,

Look in the [develop](https://github.com/odinuge/tt-to-subrip/tree/develop)-branch, and report whether it works or not!

Thanks!

**Comment by rafamerino** [comment]
Perfect! Now SRT files works like a charm with the vids.

Thank you so much. Kudos for you!!
